import Head from 'next/head'
import Messenger from './Messenger/Messenger'

export default function Home() {
  return (
    <div>
      <Head>
        <title>App Chat</title>
        <meta name="description" content="Generated by JoamCriff" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Messenger />
    </div>
  )
}
 